version: '3.8'

services:
  web:
    build: .
    image: omu_develop_teamd_image
    container_name: omu_develop_teamd_container
    ports:
      - "9000:80"
    command: bash -c "sh /etc/startup.sh && httpd-foreground"
